package com.example.springproject.model.enums;

public enum Region {
    TUNIS, ARIANA, BEN_AROUS, MANOUBA,
    NABEUL, ZAGHOUAN, BIZERTE, BEJA, JENDOUBA, LE_KEF, SILIANA,
    KAIROUAN, KASSERINE, SIDI_BOUZID,
    SOUSSE, MONASTIR, MAHDIA,
    SFAX, GABES, MEDENINE, TATAOUINE,
    GAFSA, TOZEUR, KEBILI, AUTRE
}
